name: GitHub Actions Practice Task
run-name: ${{ github.actor }} is testing and building Python modules
on: [push]
jobs:
  Test-and-build-modules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Create temporary directories
      run: |
        mkdir logs
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Test with unittest
      continue-on-error: true
      run: |
        pip install -U unittest-xml-reporting
        python src/tester.py
        
    - name: Upload artifact results.xml
      uses: actions/upload-artifact@v2
      with: 
        name: results.xml
        path: logs
      continue-on-error: false
        
    - name: Build modules
      run: |
        pip install -U pyinstaller
        pyinstaller --onefile src/solver_add.py
        pyinstaller --onefile src/solver_subtract.py
        
    - name: Upload artifact solver_add
      uses: actions/upload-artifact@v2
      with: 
        name: solver_add
        path: dist/solver_add
        
    - name: Upload artifact solver_subtract
      uses: actions/upload-artifact@v2
      with: 
        name: solver_subtract
        path: dist/solver_subtract
        



